# Generated by Django 3.2.16 on 2023-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='iACPzm', max_length=6, verbose_name='invite code'),
        ),
    ]
