# Generated by Django 3.2.16 on 2023-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='5JFMAn', max_length=6, verbose_name='invite code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='username'),
        ),
    ]
