# Generated by Django 3.2.16 on 2023-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230818_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='P4kdjv', max_length=6, verbose_name='invite code'),
        ),
    ]
