# Generated by Django 3.2.16 on 2023-08-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230818_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.PositiveIntegerField(default=1234, verbose_name='passcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='zQUoGC', max_length=6, verbose_name='invite code'),
        ),
    ]
