# Generated by Django 3.2.16 on 2023-08-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230818_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='mvg3A8', max_length=6, unique=True, verbose_name='invite code'),
        ),
    ]
