# Generated by Django 3.2.16 on 2023-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='V33EN6', max_length=6, unique=True, verbose_name='referal code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.PositiveIntegerField(null=True, verbose_name='passcode'),
        ),
    ]
